name: 'Prepare static NextJS build'
description: 'Prepare static NextJS build, exported to ./out'
inputs:
  version:
    description: 'Build version to be displayed on front-end.'
    required: false
  environment:
    description: 'Build environment to be displayed on front-end.'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: echo "NEXT_PUBLIC_BUILD_VERSION=${{ inputs.version }}" >> $GITHUB_ENV   
      shell: bash
    - run: echo "NEXT_PUBLIC_BUILD_ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV      
      shell: bash
    - run: echo "NEXT_PUBLIC_COMMIT_ID=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      shell: bash
    - id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - run: npm i
      shell: bash
    - run: npm run lint
      shell: bash
    - run: npm run build
      shell: bash
    - run: npm run export
      shell: bash